### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by ashes999** [MuslimGamer/virus-escape#1]
**Reminder:** Cut absolutely everything non-essential. Images, UI, tutorials, it's all skippable; we need to make sure the game is fun.

# MVP Ideas: Is It Fun Yet? (Stop If Yes)

- [x] @ashes999 Generate a 20x20 grid (blue squares, for example, with borders if easy)
- [x] @ashes999 unit-testing infrastructure + `map` tests
- [x] @NegativeScript  Randomly place the player somewhere on the grid
- [x] @NegativeScript  Walking around
  - [x] WASD/arrows to move around, move tile by tile
  - [x] Can't walk off the grid
- [x] @NegativeScript Generate a win gate randomly somewhere on-grid (green please)
- [x] @NegativeScript Touching the gate takes you to the next level (print the level number using `console.log`)
- [x] @NegativeScript Generate some red tiles that kill you on touch (`console.log` a you-die message and restart)
- [x] @NegativeScript On level `n`, generate `n` red tiles randomly placed
- [x] Map class has a `seed` parameter, which seeds the random; defaults to "generate a value"; `console.log` it in constructor.
- [x] If `config.json` has a `seed` value, use that as the game seed
- [x] @NegativeScript Generate a switch-gate; the gate kills you if you walk on it, but pressing the switch removes it
- [x] @NegativeScript Generate `(n/2) + 1` switch-gates on level `n`
- [x] @NegativeScript Put a timer with a time-limit and you die if it runs out; put it behind a config switch.
- [x] @NegativeScript Change level generation to use a seed.
- [x] Feature toggle to switch between time limit (seconds left) and move limit (turns left).
- [x] Feature (+toggle): HP. You have `10` to start (config it), eating a death gate drops it by `5` (also configurable).
- [x] Feature (+toggle): generate impregnable death-gates too.
- [x] Feature (+toggle): every 10 seconds, a random tile gets scanned and turns orange. It's a wall.
  - [x] Sub-feature: every 20 seconds, an orange tile turns RED and can kill you.
  - [x] @NegativeScript  figure out which (red/orange) should subtract health and which are impregnable, and code it appropriately so you can break the breakable ones
- [x] @NegativeScript Add visual indicator linking switch and switchGate
- [x] @NegativeScript Add antivirus entities that hunt the player down When the player moves (once|twice|configurable), they move once.
- [x] Add wall generation.
- [ ] Add configuration option for decrementing health on moving.
- [x] Add configuration option for passable but un-disable-able pink tiles.
- [ ] Need interesting maps, eg. with choke-holds and only one path to victory. Even at level 1.
- [x] Allow passing a tick by pressing space.

# Bugs
- [x] You can spawn adjacent or very close to the exit.
- [ ] Default seed (1531171161), first ~10 levels, exit is wide open. No interaction necessary.
- [ ] Seed 28855793, level 20 is impossible
- [x] Anti-Virus trails don't disappear after they're killed.
- [x] *Some* Anti-Virus trails don't disappear after they're killed.
- [x] At higher levels, too many tiles than there *are* try to spawn, crashing the game.

**Comment by NegativeScript** [comment]
Note: changed my name from @PythonWantsBoop to @NegativeScript.

**Comment by NegativeScript** [comment]
We can use http://easystarjs.com/ for A* path finding.

**Comment by ashes999** [comment]
@NegativeScript it looks like you deleted your comment about A* path-finding. I found a different lib, but sure, we can try that one first; let me know if you're interested in doing this ,and in writing QUnit unit tests.

**Comment by NegativeScript** [comment]
I've never written QUnit tests before, but looking at your examples, and after some googling, I think I can manage some.

As for the pathfinding, I may decide to take it later, if nobody does.

**Comment by NegativeScript** [comment]
Fixed the bug, I don't see the use of unit tests for that anymore. It'll take care of itself.

**Comment by ashes999** [comment]
I still need the unit tests to verify that every possible level with every possible seed is beatable.

**Comment by NegativeScript** [comment]
Fair enough. Hopefully, it'll happen Soon™.

**Comment by ashes999** [comment]
MVP is done.
