### ISSUE TITLE
Bug: Seed 2828407160: anti-virus walks over you

### ISSUE THREAD

**Issue by ashes999** [MuslimGamer/virus-escape#19]
Repro steps:

- Start a game on seed 2828407160
- Hit space twice

The nearest anti-virus will walk over top of you.  If you keep hitting space, the game progresses, and you don't die.

**Comment by ashes999** [comment]
Figured out a similar bug; if there's one (say, vertical) space between you and an anti-virus, and you both move into the space on your next turn, it doesn't die, and you "disappear" under it.

**Comment by NegativeScript** [comment]
>The nearest anti-virus will walk over top of you. If you keep hitting space, the game progresses, and you don't die.

This is supposed to happen, but the player shouldn't be allowed to stand around with an anti-virus on their head. I should add a per-tick check to continuously reduce health.

>Figured out a similar bug; if there's one (say, vertical) space between you and an anti-virus, and you both move into the space on your next turn, it doesn't die, and you "disappear" under it.

This is also supposed to happen. In the game, the player moves first. And if an anti-virus steps on the player, the player gets hurt. Same check as above should do the trick.

**Comment by ashes999** [comment]
> This is supposed to happen, but the player shouldn't be allowed to stand around with an anti-virus on their head.

This is a bug. The player EATS antivirii for breakfast. They should never co-occupy a tile.

> This is also supposed to happen. In the game, the player moves first. And if an anti-virus steps on the player, the player gets hurt. Same check as above should do the trick.

This is also a bug. Anti-viruses don't decrease health; we consume them. They should be consumed. If that has a health penalty, so be it; but co-occupying tiles should never happen.
